### ISSUE TITLE
Anyplace v3.0.4 - getting error while uploading floor image

### ISSUE THREAD

**Issue by dsudheer** [dmsl/anyplace#148]
Hi Team,
I just started exploring anyplace application. I liked the application very much and trying to deploy latest v3.0.4 version locally. Everything went well until I tried to add floor map. The floor entry record created successfully and next step image upload is failed with 500 error. Below is the console log. Am I doing anything wrong here?
Log:
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.None$.get(Option.scala:345) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at oauth.provider.v2.models.OAuth2Request.assertJsonBody(OAuth2Request.scala:65) ~[anyplace_v3.anyplace_v3-0.3b-sans-externalized.jar:na]
	at oauth.provider.v2.models.OAuth2Request.<init>(OAuth2Request.scala:56) ~[anyplace_v3.anyplace_v3-0.3b-sans-externalized.jar:na]
	at oauth.provider.v2.models.OAuth2Request.<init>(OAuth2Request.scala:61) ~[anyplace_v3.anyplace_v3-0.3b-sans-externalized.jar:na]
	at controllers.AnyplaceMapping$$anonfun$floorPlanUpload$1.apply(AnyplaceMapping.scala:1712) ~[anyplace_v3.anyplace_v3-0.3b-sans-externalized.jar:na]
	at controllers.AnyplaceMapping$$anonfun$floorPlanUpload$1.apply(AnyplaceMapping.scala:1710) ~[anyplace_v3.anyplace_v3-0.3b-sans-externalized.jar:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
[error] application - 

! @75100c40h - Internal server error, for (POST) [/anyplace/mapping/floor/upload] ->
 
play.api.UnexpectedException: Unexpected exception[NoSuchElementException: None.get]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]

Thanks,
Sudheer

**Comment by Costantinos** [comment]
Dear Sudheer,

Thank you for reporting the issue. We have already updated the source code under the develop branch. You can git pull the latest code or download the updated distribution package under https://anyplace.cs.ucy.ac.cy/downloads/anyplace_v3.zip.

Best regards,
Anyplace team

**Comment by dsudheer** [comment]
Thank you. Still building not uploading from UI. Getting different error now. Here is the log.

[info] application - LPLogger::Info:: requested: floor_plans/building_6c0c3699-df5a-40ba-a298-abb92edbfef2_1502340597370/fl_0/fl_0
[info] application - LPLogger::Info:: Floorplan Request[json]: {"top_right_lat":"17.42282437114256","buid":"building_6c0c3699-df5a-40ba-a298-abb92edbfef2_1502340597370","owner_id":"110964350376091692963_google","bottom_left_lat":"17.422612540954713","top_right_lng":"78.54501469852536","floor_number":"0","bottom_left_lng":"78.54479276331412"}
[info] application - LPLogger::Info:: Floorplan Request[floorplan]: blob
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
java.lang.NullPointerException: null
	at utils.AnyPlaceTilerHelper$.tileImage(AnyPlaceTilerHelper.scala:86) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at controllers.AnyplaceMapping$$anonfun$floorPlanUpload$1.apply(AnyplaceMapping.scala:1759) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at controllers.AnyplaceMapping$$anonfun$floorPlanUpload$1.apply(AnyplaceMapping.scala:1710) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]

**Comment by Costantinos** [comment]
Hello, 

The Anyplace tiler service is written in python. You need to install python on your system in order to run the Anyplace tiler service.

Best regards,
Anyplace team

**Comment by dsudheer** [comment]
Thank you for quick reply. I too have python on my machine. I see below code is not working as expected, this is returning as null. copying image to local server have some problem. Folders are creating but not the file. I am using Ubuntu LTS 16.
 floor_file = AnyPlaceTilerHelper.storeFloorPlanToServer(buid, floor_number, floorplan.ref.file) 

Thank you,
Sudheer

**Comment by kgeorgiou** [comment]
@dsudheer make sure that the tiler scripts have executable permissions:
```
$ cd server/anyplace_tiler
$ chmod +x *.py *.sh
```

**Comment by dsudheer** [comment]
Thanks Team.
I see below code is not working. I have added some loggers and change in file copy logic still no luck. we are getting '**dest_f**' as null at the end. Can someone check whats wrong with this code?

**AnyPlaceTilerHelper.scala**
    def storeFloorPlanToServer(buid: String, floor_number: String, file: File): File = {
        val dirS = AnyPlaceTilerHelper.getRootFloorPlansDirFor(buid, floor_number)
        val dir1 = new File(dirS)
        dir1.mkdirs()
        if (!dir1.isDirectory || !dir1.canWrite() || !dir1.canExecute()) {
            throw new AnyPlaceException("Floor plans directory is inaccessible!!!")
        }
        val name = "fl" + "_" + floor_number
        LPLogger.info(dir1.getAbsolutePath() +"/"+ name);
        val dest_f = new File(dir1.getAbsolutePath() +"/"+ name);
        LPLogger.info("dest_f.getAbsolutePath():"+dest_f.getAbsolutePath());
        var fout: FileOutputStream = null
        fout = new FileOutputStream(dest_f)
        fout.close()
        LPLogger.info("file.toPath()"+file.toPath());
        Files.copy(file.toPath(), dest_f.toPath())
       // println(dest.getAbsolutePath())
       // Files.copy(file.toPath(), fout)
        
        LPLogger.info("dest_f:"+dest_f);

        dest_f
    }



Thanks,
Sudheer
