### ISSUE TITLE
Exception while uploading floor plan

### ISSUE THREAD

**Issue by abhilash1in** [dmsl/anyplace#168]
```
[info] application - LPLogger::Info:: AnyplaceMapping::buildingAll(): {"username":"username","password":"password"}
{"name":" 星网:"}
 星网:
[info] application - LPLogger::Info:: AnyplaceMapping::buildingAdd(): {"description":"-","name":"Test","is_published":"false","address":"-","url":"-","bucode":"","owner_id":"105231846259501840877_google","coordinates_lat":"12.971493216039617","coordinates_lon":"77.54233002662659","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImVmMWU4OGM1MzEzOWEwMTgwODU2M2Y5YmU3OTc5NDcwMTcxODk1MTMifQ.eyJhenAiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDUyMzE4NDYyNTk1MDE4NDA4NzciLCJlbWFpbCI6ImFiaGlsYXNoMWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiTW5FZW1uVFNHZXppaHBjZV9LdlZ1ZyIsImNfaGFzaCI6Ilo2WXBodldqWGpJUXR3WUVyTklnYlEiLCJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwianRpIjoiNjcwNzZlYWE0NWRjYzFlYjhjMmQwOTY5ODg3MWFlNDE3OTNmYzZjYSIsImlhdCI6MTUwODQzNzAwNCwiZXhwIjoxNTA4NDQwNjA0fQ.sg2DxNHWGBnlWM4OnTpPK9HF4Fpp-MfkIeTVjL8Vna-ZMLtgxcDIRM-gDxGqd29JpKNsX04x8n6SmLqGiW5grR1BRF0ZkUbMAulQ4Iih8ARpCeHds5l5RXCQpH8LxRzSAxjqnbJdNj7tY9Qht_hpGZTS5D1Wgrn03AlrZ9SCMDobTFw6nlLgjfVExAFgFM3rgETwjZaOB62-vm0GVAokfTtMfPYh0kRK4kDi-yV_9FCxfvGg5TS3A9KXR2RXn5o-vMjJ66-ERrhDGO1Q4JP6_cPW1lBGG8q9lOL-YwCD5xV-Y__A0Rlr0EbVjrSsqKnwDCRUsxQkhgIaCRoqU_MokA"}
[info] application - LPLogger::Info:: AnyplaceMapping::floorAll(): {"username":"username","password":"password","buid":"building_ea7381b2-b72a-4157-9fef-de076007600a_1508437409737","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImVmMWU4OGM1MzEzOWEwMTgwODU2M2Y5YmU3OTc5NDcwMTcxODk1MTMifQ.eyJhenAiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDUyMzE4NDYyNTk1MDE4NDA4NzciLCJlbWFpbCI6ImFiaGlsYXNoMWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiTW5FZW1uVFNHZXppaHBjZV9LdlZ1ZyIsImNfaGFzaCI6Ilo2WXBodldqWGpJUXR3WUVyTklnYlEiLCJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwianRpIjoiNjcwNzZlYWE0NWRjYzFlYjhjMmQwOTY5ODg3MWFlNDE3OTNmYzZjYSIsImlhdCI6MTUwODQzNzAwNCwiZXhwIjoxNTA4NDQwNjA0fQ.sg2DxNHWGBnlWM4OnTpPK9HF4Fpp-MfkIeTVjL8Vna-ZMLtgxcDIRM-gDxGqd29JpKNsX04x8n6SmLqGiW5grR1BRF0ZkUbMAulQ4Iih8ARpCeHds5l5RXCQpH8LxRzSAxjqnbJdNj7tY9Qht_hpGZTS5D1Wgrn03AlrZ9SCMDobTFw6nlLgjfVExAFgFM3rgETwjZaOB62-vm0GVAokfTtMfPYh0kRK4kDi-yV_9FCxfvGg5TS3A9KXR2RXn5o-vMjJ66-ERrhDGO1Q4JP6_cPW1lBGG8q9lOL-YwCD5xV-Y__A0Rlr0EbVjrSsqKnwDCRUsxQkhgIaCRoqU_MokA"}
couchbase results: 0
[info] application - LPLogger::Info:: AnyplaceMapping::floorAdd(): {"is_published":"true","buid":"building_ea7381b2-b72a-4157-9fef-de076007600a_1508437409737","floor_name":"1","description":"1","floor_number":"1","owner_id":"105231846259501840877_google","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImVmMWU4OGM1MzEzOWEwMTgwODU2M2Y5YmU3OTc5NDcwMTcxODk1MTMifQ.eyJhenAiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDUyMzE4NDYyNTk1MDE4NDA4NzciLCJlbWFpbCI6ImFiaGlsYXNoMWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiTW5FZW1uVFNHZXppaHBjZV9LdlZ1ZyIsImNfaGFzaCI6Ilo2WXBodldqWGpJUXR3WUVyTklnYlEiLCJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwianRpIjoiNjcwNzZlYWE0NWRjYzFlYjhjMmQwOTY5ODg3MWFlNDE3OTNmYzZjYSIsImlhdCI6MTUwODQzNzAwNCwiZXhwIjoxNTA4NDQwNjA0fQ.sg2DxNHWGBnlWM4OnTpPK9HF4Fpp-MfkIeTVjL8Vna-ZMLtgxcDIRM-gDxGqd29JpKNsX04x8n6SmLqGiW5grR1BRF0ZkUbMAulQ4Iih8ARpCeHds5l5RXCQpH8LxRzSAxjqnbJdNj7tY9Qht_hpGZTS5D1Wgrn03AlrZ9SCMDobTFw6nlLgjfVExAFgFM3rgETwjZaOB62-vm0GVAokfTtMfPYh0kRK4kDi-yV_9FCxfvGg5TS3A9KXR2RXn5o-vMjJ66-ERrhDGO1Q4JP6_cPW1lBGG8q9lOL-YwCD5xV-Y__A0Rlr0EbVjrSsqKnwDCRUsxQkhgIaCRoqU_MokA"}
[info] application - LPLogger::Info:: AnyplaceMapping::serveFloorPlanBase64(): {"username":"username","password":"password","buid":"building_ea7381b2-b72a-4157-9fef-de076007600a_1508437409737","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImVmMWU4OGM1MzEzOWEwMTgwODU2M2Y5YmU3OTc5NDcwMTcxODk1MTMifQ.eyJhenAiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDUyMzE4NDYyNTk1MDE4NDA4NzciLCJlbWFpbCI6ImFiaGlsYXNoMWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiTW5FZW1uVFNHZXppaHBjZV9LdlZ1ZyIsImNfaGFzaCI6Ilo2WXBodldqWGpJUXR3WUVyTklnYlEiLCJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwianRpIjoiNjcwNzZlYWE0NWRjYzFlYjhjMmQwOTY5ODg3MWFlNDE3OTNmYzZjYSIsImlhdCI6MTUwODQzNzAwNCwiZXhwIjoxNTA4NDQwNjA0fQ.sg2DxNHWGBnlWM4OnTpPK9HF4Fpp-MfkIeTVjL8Vna-ZMLtgxcDIRM-gDxGqd29JpKNsX04x8n6SmLqGiW5grR1BRF0ZkUbMAulQ4Iih8ARpCeHds5l5RXCQpH8LxRzSAxjqnbJdNj7tY9Qht_hpGZTS5D1Wgrn03AlrZ9SCMDobTFw6nlLgjfVExAFgFM3rgETwjZaOB62-vm0GVAokfTtMfPYh0kRK4kDi-yV_9FCxfvGg5TS3A9KXR2RXn5o-vMjJ66-ERrhDGO1Q4JP6_cPW1lBGG8q9lOL-YwCD5xV-Y__A0Rlr0EbVjrSsqKnwDCRUsxQkhgIaCRoqU_MokA","floor_number":"1"}
[info] application - LPLogger::Info:: requested: floor_plans/building_ea7381b2-b72a-4157-9fef-de076007600a_1508437409737/fl_1/fl_1
[info] application - LPLogger::Info:: AnyplaceMapping::poisByFloor(): {"username":"username","password":"password","buid":"building_ea7381b2-b72a-4157-9fef-de076007600a_1508437409737","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImVmMWU4OGM1MzEzOWEwMTgwODU2M2Y5YmU3OTc5NDcwMTcxODk1MTMifQ.eyJhenAiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDUyMzE4NDYyNTk1MDE4NDA4NzciLCJlbWFpbCI6ImFiaGlsYXNoMWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiTW5FZW1uVFNHZXppaHBjZV9LdlZ1ZyIsImNfaGFzaCI6Ilo2WXBodldqWGpJUXR3WUVyTklnYlEiLCJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwianRpIjoiNjcwNzZlYWE0NWRjYzFlYjhjMmQwOTY5ODg3MWFlNDE3OTNmYzZjYSIsImlhdCI6MTUwODQzNzAwNCwiZXhwIjoxNTA4NDQwNjA0fQ.sg2DxNHWGBnlWM4OnTpPK9HF4Fpp-MfkIeTVjL8Vna-ZMLtgxcDIRM-gDxGqd29JpKNsX04x8n6SmLqGiW5grR1BRF0ZkUbMAulQ4Iih8ARpCeHds5l5RXCQpH8LxRzSAxjqnbJdNj7tY9Qht_hpGZTS5D1Wgrn03AlrZ9SCMDobTFw6nlLgjfVExAFgFM3rgETwjZaOB62-vm0GVAokfTtMfPYh0kRK4kDi-yV_9FCxfvGg5TS3A9KXR2RXn5o-vMjJ66-ERrhDGO1Q4JP6_cPW1lBGG8q9lOL-YwCD5xV-Y__A0Rlr0EbVjrSsqKnwDCRUsxQkhgIaCRoqU_MokA","floor_number":"1"}
[info] application - LPLogger::Info:: Floorplan Request[json]: {"top_right_lat":"12.97149907229914","buid":"building_ea7381b2-b72a-4157-9fef-de076007600a_1508437409737","owner_id":"105231846259501840877_google","bottom_left_lat":"12.971367068306908","top_right_lng":"77.54239117707884","floor_number":"1","bottom_left_lng":"77.54227410040933"}
[info] application - LPLogger::Info:: Floorplan Request[floorplan]: blob
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
java.lang.NullPointerException: null
	at utils.AnyPlaceTilerHelper$.tileImage(AnyPlaceTilerHelper.scala:86) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at controllers.AnyplaceMapping$$anonfun$floorPlanUpload$1.apply(AnyplaceMapping.scala:1759) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at controllers.AnyplaceMapping$$anonfun$floorPlanUpload$1.apply(AnyplaceMapping.scala:1710) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
[error] application - 

! @75l052ag8 - Internal server error, for (POST) [/anyplace/mapping/floor/upload] ->
 
play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.7.jar:na]
	at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
Caused by: java.lang.NullPointerException: null
	at utils.AnyPlaceTilerHelper$.tileImage(AnyPlaceTilerHelper.scala:86) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at controllers.AnyplaceMapping$$anonfun$floorPlanUpload$1.apply(AnyplaceMapping.scala:1759) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at controllers.AnyplaceMapping$$anonfun$floorPlanUpload$1.apply(AnyplaceMapping.scala:1710) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]

```

Couchbase Document for Building `building_ea7381b2-b72a-4157-9fef-de076007600a_1508437409737
`

```
{
  "co_owners": [],
  "geometry": {
    "type": "Point",
    "coordinate": [
      12.97149321603962,
      77.54233002662659
    ]
  }
}
```

```
{
  "buid": "building_ea7381b2-b72a-4157-9fef-de076007600a_1508437409737",
  "floor_name": "1",
  "top_right_lat": "12.97149907229914",
  "is_published": "true",
  "username_creator": null,
  "bottom_left_lat": "12.971367068306908",
  "description": "1",
  "floor_number": "1",
  "fuid": "building_ea7381b2-b72a-4157-9fef-de076007600a_1508437409737_1",
  "top_right_lng": "77.54239117707884",
  "bottom_left_lng": "77.54227410040933"
}
```

Also, the saved buildings and floor plans are not shown after a refresh of the page (though it is present in DB)

**Comment by abhilash1in** [comment]
Also, what is `{"username":"username","password":"password"}` in the logs above? I've never set `username` as the username and `password` as the password.

**Comment by JeffOnGithub** [comment]
Same issue here, you're not alone.

**Comment by JeffOnGithub** [comment]
From what i see in the code, the server cannot save the files correctly and then get a null when trying to tile a non-existing file

**Comment by anyplaceucy** [comment]
Check the latest release v3.2 and report if issue has not been addressed.
