### ISSUE TITLE
Unable to add POI.

### ISSUE THREAD

**Issue by mathurabhishek** [dmsl/anyplace#182]
I am running anyplace_v3  binaries for architect and viewer on our own server. I am able to add building and floor plan successfully but not able to add any POI. Here's the error log:

****[info] application - LPLogger::Info:: AnyplaceMapping::poisByFloor(): {"username
":"username","password":"password","buid":"building_208407a6-b20b-469e-8e9f-9225
3d88dc96_1512307643904","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImNjYWI0YWNi
MTA3OTIwZGMyODRjOTZjNjIwNWIzMTMyNzA2NzIwMzkifQ.eyJhenAiOiI1ODc1MDA3MjM5NzEtc2k4c
zRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhd
WQiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nb
GV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTQwNjMxMjA3NzAxODMzMjQwMTUiLCJlbWFpbCI6ImFia
GlzaGVraG9uZXl3ZWxsMTIzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoI
joid25fZVdWZlNFQ1lMZDlPQV95U1padyIsImNfaGFzaCI6Il95a3ppSmhPVmhDaENyR3IycFc0UGciL
CJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwianRpIjoiZWMxODJjY2ZjNzljZTBjZjUzMDdkNTM0N
mViZjExNjEyYjQyMTU1OCIsImlhdCI6MTUxMjQxMTg1NiwiZXhwIjoxNTEyNDE1NDU2fQ.i7J1SWVrqT
2Krg-tIjLt8GHdyBlX_6rFPrAlnURNjR8hcmR5fsMHiKMzIKurOLPUxmr69KfdPigMDRdgyvRyHA-poI
5TA8yk9cB792rg8HO4kqwlxkZ74GNnYe4jV_8mJKXPgD8na79bP9E9vJdGHMygfe6lBaDeT7en_iX1ar
zn2PmhUje7L5i0EuIQa0BZISVZsYwf-_MG-FU38gdRLQD4vIQVdJbnhNL98G6esX-p30coXb5awpV5xo
yLrco3YtvC3HfRJsTwG0PHAgpyMgkAphufC7bQLrqYrNGeWQptfVIdgiFQPd2Xp6MxWJ0-VG4_E7-_m2
Q3Vbpir2Gxig","floor_number":"1"}
[info] application - LPLogger::Info:: AnyplaceMapping::poisAdd(): {"buid":"build
ing_208407a6-b20b-469e-8e9f-92253d88dc96_1512307643904","floor_number":"1","floo
r_name":"Floor1","is_door":"false","is_building_entrance":"false","is_published"
:"true","description":"he","name":"he","pois_type":"Ramp","pois_type2":"","url":
"-","image":"url_to_pois_image","owner_id":"114063120770183324015_google","coord
inates_lat":"12.913246516950433","coordinates_lon":"77.62019991874695","access_t
oken":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImNjYWI0YWNiMTA3OTIwZGMyODRjOTZjNjIwNWIzMTMyN
zA2NzIwMzkifQ.eyJhenAiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW
9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI1ODc1MDA3MjM5NzEtc2k4czRxcW
F0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOi
IxMTQwNjMxMjA3NzAxODMzMjQwMTUiLCJlbWFpbCI6ImFiaGlzaGVraG9uZXl3ZWxsMTIzQGdtYWlsLm
NvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoid25fZVdWZlNFQ1lMZDlPQV95U1pady
IsImNfaGFzaCI6Il95a3ppSmhPVmhDaENyR3IycFc0UGciLCJpc3MiOiJhY2NvdW50cy5nb29nbGUuY2
9tIiwianRpIjoiZWMxODJjY2ZjNzljZTBjZjUzMDdkNTM0NmViZjExNjEyYjQyMTU1OCIsImlhdCI6MT
UxMjQxMTg1NiwiZXhwIjoxNTEyNDE1NDU2fQ.i7J1SWVrqT2Krg-tIjLt8GHdyBlX_6rFPrAlnURNjR8
hcmR5fsMHiKMzIKurOLPUxmr69KfdPigMDRdgyvRyHA-poI5TA8yk9cB792rg8HO4kqwlxkZ74GNnYe4
jV_8mJKXPgD8na79bP9E9vJdGHMygfe6lBaDeT7en_iX1arzn2PmhUje7L5i0EuIQa0BZISVZsYwf-_M
G-FU38gdRLQD4vIQVdJbnhNL98G6esX-p30coXb5awpV5xoyLrco3YtvC3HfRJsTwG0PHAgpyMgkAphu
fC7bQLrqYrNGeWQptfVIdgiFQPd2Xp6MxWJ0-VG4_E7-_m2Q3Vbpir2Gxig"}
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
java.lang.NullPointerException: null
        at db_models.Poi.getId(Poi.scala:123) ~[anyplace_v3.anyplace_v3-0.5-sans
-externalized.jar:na]
        at controllers.AnyplaceMapping$$anonfun$poisAdd$1.apply(AnyplaceMapping.
scala:960) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
        at controllers.AnyplaceMapping$$anonfun$poisAdd$1.apply(AnyplaceMapping.
scala:935) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408)
~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407)
~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.pla
y.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.pla
y.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.type
safe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$
5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$
5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
[error] application -

! @767mh1oh2 - Internal server error, for (POST) [/anyplace/mapping/pois/add] ->

play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(
HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.
scala:191) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.
typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsA
dapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.pla
y_2.11-2.4.2.jar:2.4.2]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGl
obalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGl
obalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-librar
y-2.11.7.jar:na]
        at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapt
er.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorH
andler.scala:94) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrE
lse(PlayDefaultUpstreamHandler.scala:273) [com.typesafe.play.play-netty-server_2
.11-2.4.2.jar:2.4.2]
Caused by: java.lang.NullPointerException: null
        at db_models.Poi.getId(Poi.scala:123) ~[anyplace_v3.anyplace_v3-0.5-sans
-externalized.jar:na]
        at controllers.AnyplaceMapping$$anonfun$poisAdd$1.apply(AnyplaceMapping.
scala:960) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
        at controllers.AnyplaceMapping$$anonfun$poisAdd$1.apply(AnyplaceMapping.
scala:935) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408)
~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407)
~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.pla
y.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.pla
y.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.type
safe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$
5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$
5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]****

It seems that null is not handled at : db_models.Poi.getId(Poi.scala:123).
When a POI is added from backend (Json import through couchbase server interface), even moving POI results in the same error. Please help in resolving this..

**Comment by shantanubanerjee** [comment]
Also I am facing same issue. @Costantinos @anyplaceucy It will be very helpful if you help us to resolve the issue...

**Comment by Maaaas** [comment]
I've run into the same problem and would appreciate any help if anyone has a solution.

**Comment by Edfischell** [comment]
I have also encountered this issue,

Is it a config issue?

**Comment by sreejith-ms** [comment]
I'm also facing the same issue. Also it will be helpful if anyone can guide me how to debug the application, currently I can run the application on IJ idea but breakpoints not been hit also tried running in debug mode.

```
! @770c3p3k7 - Internal server error, for (POST) [/anyplace/mapping/pois/add] ->
 
play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.7.jar:na]
	at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.7.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.7.jar:na]
Caused by: java.lang.NullPointerException: null
	at db_models.Poi.getId(Poi.scala:123) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at controllers.AnyplaceMapping$$anonfun$poisAdd$1.apply(AnyplaceMapping.scala:960) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at controllers.AnyplaceMapping$$anonfun$poisAdd$1.apply(AnyplaceMapping.scala:935) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at scala.Option.map(Option.scala:146) [org.scala-lang.scala-library-2.11.7.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	... 6 common frames omitted
```
![sketch1](https://user-images.githubusercontent.com/13817581/36014396-9a8a4e9c-0d8f-11e8-89a7-94449a74f323.png)

![sketch2](https://user-images.githubusercontent.com/13817581/36014397-9ad5063a-0d8f-11e8-902e-ce235b05622e.png)

**Comment by Costantinos** [comment]
Hello,

There was a small bug at Poi class. The develop branch has been updated.

**Comment by sreejith-ms** [comment]
@Costantinos can you please update the binaries with the stable dev branch?
Because right now the binaries from https://anyplace.cs.ucy.ac.cy/downloads/anyplace_v3.zip is broken by these bugs.

**Comment by Costantinos** [comment]
The anyplace_v3.zip has been updated.
