### ISSUE TITLE
[KeyValueEndpoint]: Authentication Failure and buildings cannot be added

### ISSUE THREAD

**Issue by safrazd** [dmsl/anyplace#189]
I downloaded anyplace v3 folder for Administrators. After editing the config file and running the Anyplace batch file, an authentication failure error shows in the command prompt. I can launch the app via localhost:9000/architect which shows the map and option to add buildings. However, when i try adding a building, it does not add and when i am on localhost:9000/viewer, there is an error stating cannot fetch buildings.
[log_extract.txt](https://github.com/dmsl/anyplace/files/1595513/log_extract.txt)

**Comment by sreejith-ms** [comment]
I'm facing the same issue.

[warn] application - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] application - Global::onStart():: AnyPlace Application started
[info] application - Trying to connect to: http://127.0.0.1:8091 bucket[anyplace] password: Administrator
[warn] c.c.c.c.e.Endpoint - [null][KeyValueEndpoint]: Authentication Failure.
[warn] c.c.c.c.e.Endpoint - [null][KeyValueEndpoint]: Authentication Failure.
[warn] c.c.c.c.e.Endpoint - [null][KeyValueEndpoint]: Authentication Failure.
[warn] c.c.c.c.e.Endpoint - Error during reconnect:
com.couchbase.client.core.endpoint.kv.AuthenticationException: Authentication Failure
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.checkIsAuthed(KeyValueAuthHandler.java:288) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:173) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:52) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
[warn] c.c.c.c.e.Endpoint - Error during reconnect:
com.couchbase.client.core.endpoint.kv.AuthenticationException: Authentication Failure
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.checkIsAuthed(KeyValueAuthHandler.java:288) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:173) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:52) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
[warn] c.c.c.c.e.Endpoint - [null][KeyValueEndpoint]: Could not connect to endpoint, retrying with delay 32 MILLISECONDS:
com.couchbase.client.core.endpoint.kv.AuthenticationException: Authentication Failure
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.checkIsAuthed(KeyValueAuthHandler.java:288) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:173) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:52) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
[warn] c.c.c.c.e.Endpoint - [null][KeyValueEndpoint]: Could not connect to endpoint, retrying with delay 32 MILLISECONDS:
com.couchbase.client.core.endpoint.kv.AuthenticationException: Authentication Failure
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.checkIsAuthed(KeyValueAuthHandler.java:288) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:173) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:52) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
[warn] c.c.c.c.e.ResponseStatusConverter - Unknown ResponseStatus with Protocol HTTP: 401
[warn] c.c.c.c.e.Endpoint - [null][KeyValueEndpoint]: Authentication Failure.
[warn] c.c.c.c.e.Endpoint - Error during reconnect:
com.couchbase.client.core.endpoint.kv.AuthenticationException: Authentication Failure
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.checkIsAuthed(KeyValueAuthHandler.java:288) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:173) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:52) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
[warn] c.c.c.c.e.Endpoint - [null][KeyValueEndpoint]: Could not connect to endpoint, retrying with delay 32 MILLISECONDS:
com.couchbase.client.core.endpoint.kv.AuthenticationException: Authentication Failure
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.checkIsAuthed(KeyValueAuthHandler.java:288) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:173) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:52) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
[warn] c.c.c.c.e.Endpoint - [null][KeyValueEndpoint]: Authentication Failure.
[warn] c.c.c.c.e.Endpoint - Error during reconnect:
com.couchbase.client.core.endpoint.kv.AuthenticationException: Authentication Failure
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.checkIsAuthed(KeyValueAuthHandler.java:288) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:173) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:52) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
[warn] c.c.c.c.e.Endpoint - [null][KeyValueEndpoint]: Could not connect to endpoint, retrying with delay 32 MILLISECONDS:
com.couchbase.client.core.endpoint.kv.AuthenticationException: Authentication Failure
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.checkIsAuthed(KeyValueAuthHandler.java:288) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:173) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:52) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [com.couchbase.client.core-io-1.4.5.jar:na]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [com.couchbase.client.core-io-1.4.5.jar:na]
[warn] c.c.c.c.e.ResponseStatusConverter - Unknown ResponseStatus with Protocol HTTP: 401
[error] application - LPLogger::Error:: CouchbaseDatasource::connect():: Error connection to Couchbase: Passwords for bucket "anyplace" do not match.
[error] application - LPLogger::Error:: CouchbaseDatasource::init():: Cannot connect to Anyplace Database! [Unknown]
[error] application - LPLogger::Error:: CouchbaseDatasource::getStaticInstance():: Exception while instantiating Couchbase [Cannot establish connection to Anyplace database!]
[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

**Comment by Costantinos** [comment]
Hello,

Did you put the correct password for the couchbase in the configuration? From you log, It seems that username and password are wrong.
The anyplace v3 have been tested and it is working with couchbase 4.5.

**Comment by sreejith-ms** [comment]
@Costantinos Thanks for the reply. The username and password is correct. I fixed this issue by creating a user with the bucket name. 

https://stackoverflow.com/a/44399097/
https://stackoverflow.com/a/47171398/
