### ISSUE TITLE
unable to add floor

### ISSUE THREAD

**Issue by m6amiri** [dmsl/anyplace#191]
I am running anyplace_v3  for architect and viewer on my own server using intelliJ. I am able to add building but  i can not add floor plan.  Here's the error log:
! @76j7jpf70 - Internal server error, for (POST) [/anyplace/mapping/floor/add] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IllegalMonitorStateException: null]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.2.jar:2.4.2]
	at scala.Option.getOrElse(Option.scala:121) [scala-library-2.11.7.jar:na]
	at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [play-netty-server_2.11-2.4.2.jar:2.4.2]
Caused by: java.lang.IllegalMonitorStateException: null
	at java.lang.Object.wait(Native Method) ~[na:1.8.0_151]
	at controllers.AnyplaceMapping$$anonfun$floorAdd$1.apply(AnyplaceMapping.scala:813) ~[classes/:na]
	at controllers.AnyplaceMapping$$anonfun$floorAdd$1.apply(AnyplaceMapping.scala:786) ~[classes/:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.2.jar:2.4.2]

**Comment by m6amiri** [comment]
solved

**Comment by Maaaas** [comment]
@m6amiri Hey I've run into a similar problem and was wondering if you could explain what you did to solve your issue? Thanks!

**Comment by m6amiri** [comment]
add the following condition to db_model/floor to check if buid is null:
line: 97:   if (buid==null  ||  buid.isEmpty   ||   buid == "") {
            val finalId = LPUtils.getRandomUUID + "_" + System.currentTimeMillis()

do this for poi too
