### ISSUE TITLE
Something went wrong while fetching route

### ISSUE THREAD

**Issue by thedaini** [dmsl/anyplace#209]
I receive an error when trying to view the route between POIs.  UI says "Something went wrong while fetching route".

Console log:
```
[error] application -

! @777aj5kok - Internal server error, for (POST) [/anyplace/navigation/route] ->

play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.7.jar:na]
        at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.filters.cors.AbstractCORSPolicy$$anonfun$1.applyOrElse(AbstractCORSPolicy.scala:151) [com.typesafe.play.filters-helpers_2.11-2.4.2.jar:2.4.2]
Caused by: java.lang.NullPointerException: null
        at java.text.DecimalFormat.parse(DecimalFormat.java:1997) ~[na:1.8.0_161]
        at java.text.NumberFormat.parse(NumberFormat.java:383) ~[na:1.8.0_161]
        at utils.Dijkstra$Graph$$anonfun$addEdges$1.apply(Dijkstra.scala:72) ~[anyplace_v3.anyplace_v3-2.0-sans-externalized.jar:na]
        at utils.Dijkstra$Graph$$anonfun$addEdges$1.apply(Dijkstra.scala:70) ~[anyplace_v3.anyplace_v3-2.0-sans-externalized.jar:na]
        at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at utils.Dijkstra$Graph.addEdges(Dijkstra.scala:70) ~[anyplace_v3.anyplace_v3-2.0-sans-externalized.jar:na]
        at controllers.AnyplaceNavigation$.navigateSameFloor(AnyplaceNavigation.scala:229) ~[anyplace_v3.anyplace_v3-2.0-sans-externalized.jar:na]
```

**Comment by Costantinos** [comment]
Hello,

We have updated the code and the binaries. Could you please download the latest version and check if the problem is solved.

**Comment by thedaini** [comment]
I built the updated code base and it works now.  Thank you!
