### ISSUE TITLE
Why my anyplace could not connect couchbase?

### ISSUE THREAD

**Issue by camelgg** [dmsl/anyplace#312]
# Couchbase configuration
# ~~~~~
couchbase.hostname="http://localhost"
couchbase.port=8091
couchbase.bucket="anyplace"
couchbase.username="anyplace"
couchbase.password="123456"

2019-11-28 10:05:22,069 [INFO] from play.api.libs.concurrent.ActorSystemProvider in pool-4-thread-1 - Starting application default Akka system: application
2019-11-28 10:05:22,574 [INFO] from play.core.server.NettyServer in pool-4-thread-1 - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
2019-11-28 10:22:06,890 [WARN] from application in ForkJoinPool-1-worker-1 - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
2019-11-28 10:22:09,054 [INFO] from play.api.libs.concurrent.ActorSystemProvider in ForkJoinPool-1-worker-1 - Starting application default Akka system: application
2019-11-28 10:22:10,130 [INFO] from application in ForkJoinPool-1-worker-1 - Global::onStart():: AnyPlace Application started
2019-11-28 10:22:10,329 [INFO] from application in ForkJoinPool-1-worker-1 - Trying to connect to: http://localhost:8091 bucket[anyplace] password: 123456
2019-11-28 10:22:15,079 [WARN] from com.couchbase.client.core.endpoint.Endpoint in cb-io-1-1 - [null][KeyValueEndpoint]: Could not connect to remote socket.
2019-11-28 10:22:16,093 [WARN] from com.couchbase.client.core.endpoint.Endpoint in cb-io-1-2 - [null][KeyValueEndpoint]: Could not connect to remote socket.
2019-11-28 10:22:16,109 [WARN] from com.couchbase.client.core.endpoint.Endpoint in cb-io-1-2 - Error during reconnect: 
com.couchbase.client.deps.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:11210
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_231]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_231]
	at com.couchbase.client.deps.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:258) ~[core-io-1.4.5.jar:na]
	at com.couchbase.client.deps.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291) ~[core-io-1.4.5.jar:na]
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:613) [core-io-1.4.5.jar:na]
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:560) [core-io-1.4.5.jar:na]
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:477) [core-io-1.4.5.jar:na]
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:439) [core-io-1.4.5.jar:na]
	at com.couchbase.client.deps.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) [core-io-1.4.5.jar:na]
	at com.couchbase.client.deps.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [core-io-1.4.5.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

**Comment by deemonnn** [comment]
Even I was getting the same issue and here's how i resolved...
I made the changes to both the application.conf files ie.
     i. anyplace-master\server\conf\application.conf and 
     ii. anyplace_v3\conf\application.conf

Try doing this, it might work
cheers
